### ISSUE TITLE
Top-left menu link to SI homepage is broken

### ISSUE THREAD

**Issue by craSH** [SecurityInnovation/Smart-Contract-CTF#1]
The top-left corner link to the SI home page is a messed up anchor link as it starts with a ``#``, needs to be absolute.

Currently links to: ``http://blockchain-ctf.securityinnovation.com/#/https://securityinnovation.com``

Rendered code:
```<a target="_blank" class="pure-menu-link" href="#/https://securityinnovation.com">Security Innovation</a>```

**Comment by mickayz** [comment]
Fixed in commit 70d441221f2a81f16cad790ef5685e82d25beaf0
