### ISSUE TITLE
Faucet Server Responding with Error 500

### ISSUE THREAD

**Issue by Kyperr** [SecurityInnovation/Smart-Contract-CTF#2]
Requesting ETH from the server after a proper setup results in an error 500 printed to the console.

**Comment by mickayz** [comment]
Which faucet are you using? Unfortunately the faucets are out of our control, but if one is not working I can remove it.

**Comment by Kyperr** [comment]
Not sure how to specify which one.
https://faucet.metamask.io/
On Ropsten Testnet, it times out.

Edit: As issues typically go, it's now working.
